spring:
  profiles.active: local
  application:
    name: nuek
  session:
    store-type: none

logging.level:
  com.santander.san.merchant.MerchantApplication: ${env.tech-log}
  root: ${env.root-log}



springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  use-fqn: true


app:
  cos:
    jweurl: ${env.commerce-portal.cos.jwe-url}
    keyalias: ${env.commerce-portal.cos.keyalias}
    santander-client-id: ${env.commerce-portal.cos.santander-client-id}
  sas:
    auth-url: ${env.commerce-portal.sas.auth-url}
    credential-type-jwt: ${env.commerce-portal.sas.credential-type-jwt}
    credential-type-token-corp: ${env.commerce-portal.sas.credential-type-token-corp}
    uid: ${env.commerce-portal.sas.uid}
    password: ${env.commerce-portal.sas.password}
    realm: ${env.commerce-portal.sas.realm}
  nuek:
    commerces: ${env.commerce-portal-portal.commerces-url}